name: Build, Lint and Test Lib

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
      - releaseV12-WIP

jobs:
  build_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Node.js 14.15
        uses: actions/setup-node@v1
        with:
          node-version: 14.15

      - name: Installing Dependencies
        run: sudo npm install

      - name: Linting Frontend
        run: sudo npm run lint-lib

      - name: Testing Frontend
        run: sudo npm run test-lib-ci

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: './coverage/angular-auth-oidc-client/lcov.info'

      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          parallel-finished: true

      - name: Building Frontend
        run: sudo npm run build-lib-prod

      - name: Create new Angular Project and install lib in it, test it and build it
        run: |
          cd ..
          echo '=== Current Directory ==='
          ls
          sudo npm install -g @angular/cli
          echo 'Creating new angular project'
          sudo ng new testProject --skip-git --skip-install
          cd testProject
          echo '=== Current Directory ==='
          ls
          sudo npm install --unsafe-perm=true
          sudo npm install ../angular-auth-oidc-client/dist/angular-auth-oidc-client
          npm test -- --watch=false --browsers=ChromeHeadless
          sudo npm run build -- --prod

      - name: Create new Angular Project and use the schematics to add a module
        run: |
          cd ..
          echo '=== Current Directory ==='
          ls
          sudo npm install -g @angular/cli
          echo 'Creating new angular project'
          sudo ng new testProjectSchematic --skip-git --skip-install
          cd testProjectSchematic
          echo '=== Current Directory ==='
          ls
          sudo npm install --unsafe-perm=true
          sudo ng add ../angular-auth-oidc-client/dist/angular-auth-oidc-client --authority-url-or-tenant-id "my-authority-url" --flow-type "OIDC Code Flow PKCE using iframe silent renew" --skip-confirmation
          npm test -- --watch=false --browsers=ChromeHeadless
          sudo npm run build -- --prod
